version: '3.5'

services:
  disenos-alitorres:
    image: disenos-alitorres:1.0
    build:
      context: '.'
      dockerfile: Dockerfile
      args:
        uid: ${UID}
    container_name: disenos-alitorres
    ports:
      - 9698:80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_DATABASE=lara2
      - DB_USERNAME=root
      - DB_PASSWORD=
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      disenos-alitorres:
        aliases:
          - app

networks:
  disenos-alitorres:
    name: disenos-alitorres-network