<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contrato Privado de Promesa de Venta</title>
    <link rel="stylesheet" href={{asset('css/contrato.css')}}>
    
</head>
<body>

    <div class="header">
        <img src={{asset('img/olivar.png')}} alt="Imagen Izquierda" class="header-image">
        <h1>CONTRATO PRIVADO DE PROMESA DE VENTA</h1>
        <div class="header-text">
        <p> Calle Manuel Pardo # 636 Urb, San Luis</p>
        <p>Chiclayo – Lambayeque</p>
        <p>970598300</p>
    </div>
    </div>

    <p>CONSTE POR EL PRESENTE DOCUMENTO UN <strong>CONTRATO PRIVADO DE PROMESA DE VENTA,</strong> QUE CELEBRAN DE UNA PARTE:</p>

    <div class="clause">
        <p>
        LA EMPRESA <strong>“INMOBILIARIA Y CONSTRUCTORA ALITORRES E.I.R.L”</strong>”, CON RUC N° 20605585907, CON DOMICILIO FISCAL EN CALLE MANUEL PARDO # 636, URB. SAN LUIS, DEL DISTRITO DE CHICLAYO, PROVINCIA DE CHICLAYO, DEPARTAMENTO DE LAMBAYEQUE, BAJO LA REPRESENTACIÓN LEGAL DE SU GERENTE GENERAL DON ALINDOR TORRES CHÁVEZ IDENTIFICADO CON DNI N°18986303 A TRAVÉS DE SU APODERADO, DON <strong>ELVIS HENRY TORRES SALDAÑA</strong>, DE NACIONALIDAD PERUANA, MAYOR DE EDAD, IDENTIFICADO CON DOCUMENTO NACIONAL DE IDENTIDAD Nº 42225869, ESTADO CIVIL SOLTERO, OCUPACIÓN COMERCIANTE INDEPENDIENTE, CON DOMICILIO EN CALLE ANGAMOS N° 1050 DPTO. A3 EDIFICIO SAN LUIS, URB. SAN LUIS, DEL DISTRITO DE CHICLAYO, DE LA PROVINCIA DE CHICLAYO DEL DEPARTAMENTO DE LAMBAYEQUE, SEGÚN FACULTADES INSCRITAS EN LA PARTIDA ELECTRÓNICA N°11328386, DE LA ZONA REGISTRAL N° II – SEDE CHICLAYO, A QUIEN EN ADELANTE SE LE DENOMINARA <strong>“EL PROMITENTE VENDEDOR”</strong>;</p>
    </div>
    <p>Y, DE LA OTRA:</p>
    <div class="clause">
        <p>
        DON ---------------------, DE NACIONALIDAD PERUANA, MAYOR DE EDAD, IDENTIFICADO CON DOCUMENTO NACIONAL DE IDENTIDAD N.º -----------------, ESTADO CIVIL --------------, 
        OCUPACIÓN ----------------, CON DOMICILIO EN ------------------------------, DISTRITO DE ------------, PROVINCIA DE --------------, DEPARTAMENTO DE --------------------, 
        DE TRÁNSITO POR ESTA CIUDAD, EN ADELANTE SE LE DENOMINARÁ “EL PROMITENTE COMPRADOR”. </p>
    </div>

    <div class="clause">
        <p>BAJO LOS TÉRMINOS Y CONDICIONES SIGUIENTES:</p>
        <p><strong>ANTECEDENTES </strong></p>
        <p><b><u>CLÁUSULA PRIMERA:</u></b></p>
        <p>
        <b>“EL PROMITENTE VENDEDOR”</b>, ES POSESIONARIO LEGÍTIMO DEL PREDIO DE LAS SIGUIENTES CARACTERÍSTICAS:        
        </p>
        <p><b>UBICACIÓN:</b></p>
        <ul class="custom-list">
        
            <li>SECTOR	: <b>Nº 04</b></li>
            <li>SUB SECTOR	: <b>04 A- ANCHOVIRA – BRICEÑO- CRUCE SALAS- DISTRITO DE MOTUPE, PROVINCIA DE LAMBAYEQUE, DEPARTAMENTO DE LAMBAYEQUE.</b></li>
            <li>AREA: <b>3.0274 HAS. </b></li>
            <li>PERIMETRO: <b>926.35 ML. </b></li>
            </ul>
            <p><b>LIMITES Y LINDEROS:</b></p>

            <ul class="custom-list">
            <b><li>NORTE: UCC 41013</li>
                <li>SUR: UCC 41053, UCC 41055, CALLEJÓN DE POR MEDIO.</li>
                <li>ESTE: UCC 41013, UCC 41022, UCC 41052.</li>
                <li>OESTE: CON EL RIO MOTUPE</li></b>
        </ul>
    </div>

    <div class="clause">
        <p>
        EL DERECHO DE POSESIÓN LO ACREDITA SEGÚN CERTIFICADO DE POSESIÓN OTORGADO POR LA COMUNIDAD CAMPESINA “SAN JULIAN” DE MOTUPE, REGISTRADO EN EL PADRÓN ÚNICO DE TIERRAS – PUT – EN EL LIBRO Nº 02, FOLIO N° 004-C, CON UCC Nº 41023, CON FECHA DE EMISIÓN 18/09/2021 – ADJUDICADA SEGÚN ACTA DE FECHA 21 DE NOVIEMBRE DEL 2004 BAJO LA SUSCRIPCIÓN DE DON DANILO TORRES ENRIQUEZ Y DON NATIVIDAD SOPLAPUCO PURISACA EN CALIDAD DE PRESIDENTE Y FISCAL, RESPECTIVAMENTE. DICHO ACTO JURÍDICO SE CELEBRÓ AL AMPARO DEL TÍTULO I ART. I, INC. A; ART. 7° DE LA LEY N°24656 LEY GENERAL DE LAS COMUNIDADES CAMPESINAS DEL PERÚ, Y DE LOS ARTÍCULOS 60°, 67° Y 68° DE LOS ESTATUTOS INTERNOS DE LA COMUNIDAD CAMPESINA “SAN JULIÁN” DE MOTUPE.
        </p>
    </div>

    <div class="clause">
    <p><b><u>CLÁUSULA SEGUNDA:</u></b></p>
    <p>
    <b>“EL PROMITENTE VENDEDOR”,</b> DECLARA QUE SOBRE EL PREDIO DESCRITO EN LA CLÁUSULA PRIMERA, ESTÁ DESARROLLANDO UN PROYECTO DE LOTIZACIÓN DENOMINADO<b>"VILLA EL OLIVAR"</b> - HABILITACIÓN URBANA PROGRESIVA, CONTANDO PARA TAL EFECTO CON RESOLUCIÓN COMUNAL Nº 02-2020-CCSJ-M, DE FECHA 31 DE AGOSTO DEL 2020, EN MÉRITO AL ACTA DE ASAMBLEA GENERAL ORDINARIA  DE COMUNEROS DE FECHA 27 DE AGOSTO DEL 2020, PLANO PERIMÉTRICO, DE SUPERFICIE Y LOTIZACIÓN DENOMINADA <b>“VILLA EL OLIVAR”</b>; POR LA CUAL SE DISPUSO EL CAMBIO DE USO LA PARCELA, DE USO AGRÍCOLA A USO URBANO - A NIVEL COMUNAL, CON EL OBJETO DE QUE SE CONSTITUYA EN UNA LOTIZACIÓN URBANA DENOMINADA <b>“VILLA EL OLIVAR”</b> Y SE PROCEDA A LA EJECUCIÓN DE LA MISMA.- SUSCRIBE DICHA RESOLUCIÓN: DANNY DANIEL GARAY TORRES – PRESIDENTE. 
    </p>
  </div>

  <div class="clause">
    <p><b>OBJETIVO DEL CONTRATO</b></p>
    <p><b><u>CLÁUSULA TERCERA:</u></b></p>
    <p>
    POR EL PRESENTE CONTRATO <b>“EL PROMITENTE VENDEDOR”</b> PROMETE VENDER AL <b>“PROMITENTE COMPRADOR”</b> EL INMUEBLE QUE SE DESCRIBE 
    A CONTINUACIÓN, Y CONSTITUYE A SU FAVOR DERECHO DE USO, GOCE Y HABITACIÓN, POR LO QUE EN ESTE ACTO EL PRIMERO LE ENTREGA AL SEGUNDO EL REFERIDO INMUEBLE. </p>
    <p><b>“EL PROMITENTE COMPRADOR”</b> RECIBE A SU ENTERA SATISFACCIÓN EL INMUEBLE, ASÍ COMO EL DERECHO DE USO, GOCE Y HABITACIÓN EXCLUSIVA. PREDIO PROMETIDO EN VENTA: LOTES QUE CONFORMAN LA DISTRIBUCIÓN DE PREDIAL DEL PROYECTO DE LOTIZACIÓN <b>“VILLA EL OLIVAR”, </b> EL CUAL CUENTA CON LAS SIGUIENTES CARACTERÍSTICAS:
    </p>
            <ul class="custom-list">
        
            <li>LOTE	: <b>10.</b></li>
            <li>MANZANA	: “<b>C</b>”.</li>
            <li>AREA: <b>90.00 M2. </b></li>
            </ul>

            <p>LINDEROS Y MEDIDAS PERIMETRICAS.</p>

            <ul class="custom-list">

            <li>POR EL FRENTE: <b>CON CALLE - 3, CON 6.00 ML.</b></li>
            <li>POR LA DERECHA ENTRANDO: <b>CON LOTE 9, CON 15.00 ML.</b></li>
            <li>POR LA IZQUIERDA ENTRANDO: <b>CON LOTE 11, CON 15.00 ML. </b></li>
            <li>POR EL FONDO: <b>CON LOTE 23, CON 6.00 ML. </b></li>
            </ul>


    <div class="clause">
    <p><b>PRECIO Y FORMA DE PAGO</b></p>
    <p><b><u>CLÁUSULA CUARTA:</u></b></p>
   
    <p>LAS PARTES ACUERDAN SUSCRIBIR LA PRESENTE PROMESA DE VENTA POR LA SUMA DE <b>S/. 7,000.00 (SIETE MIL CON 00/100 SOLES),</b> QUE SERÁ CANCELADO POR EL <b>“PROMITENTE COMPRADOR”</b> DE LA SIGUIENTE MANERA:</p>
    <p>A FAVOR DEL TRANSFERENTE: LA SUMA DE <b>S/ 7,000.00 (SIETE MIL CON 00/ 100 SOLES),</b> CANCELADO VÍA DEPÓSITO BANCARIO A LA CUENTA DE AHORROS DE <b>“EL PROMITENTE VENDEDOR”</b> (CUENTA N° 3059843761035 – BCP, BBVA – 001103480200394278, O CAJA PIURA - 210014282113), CON FECHA A LA SUSCRIPCIÓN, MEDIO DE PAGO QUE SE ADJUNTARÁ AL PRESENTE CONTRATO EN CALIDAD DE ANEXO. AMBAS PARTES MANIFIESTAN ORTORGAR PLENO EFECTOS CANCELATORIOS CON LA SUCRIIÓN DEL PRESENTE. LAS PARTES ACUERDAN DE CONFORMIDAD CON EL ARTICULO 1220 Y SIGUIENTES DEL CODIGO CIVIL OTORGAR EFECTOS CANCELATORIOS A LOS PAGOS QUE SEAN EFECTUADOS A <b>“EL PROMITENTE COMPRADOR”</b> COMO PRECIO DE VENTA FUTURA DE LA UNIDAD INMOBILIARIA. LAS PARTES ESTABLECEN COMO PRERROGATIVA DE <b>“EL PROMITENTE COMPRADOR”</b> AL DESISTIRSE DE LA COMPRA FUTURA DEL LOTE DE TERRENO, ACORDÁNDOSE SIN EMBARGO QUE PERDERÁ TODO LO PAGADO HASTA EL MOMENTO DEL DESISTIMIENTO SIN DERECHO A RECLAMO ALGUNO NI CONTROVERSIAS FUTURAS.</p>

    </div>
    
    <div class="clause">
    <p><b>OBLIGACIONES DE LAS PARTES</b></p>
    <p><b><u>CLÁUSULA QUINTA:</u></b></p>
    <p> DE <b>“EL PROMITENTE COMPRADOR”:</b> 1) REALIZAR PUNTUALMENTE EL PAGO MENSUAL AL QUE SE HA OBLIGADO EN EL PRESENTE CONTRATO. 2) DESOCUPAR EL PREDIO EN CASO DE DESISTIMIENTO O RESOLUCIÓN DE CONTRATO SIN MAYOR INTIMACIÓN O FORMALIDAD Y 3) GESTIONAR CARNET DE COMUNERO ANTE LA COMUNIDAD CAMPESINA “SAN JULIÁN” DE MOTUPE Y 4) ASUMIR EL COSTO DE LA GESTIÓN ANTE LA COMUNIDAD CAMPESINA “SAN JULIÁN” DE MOTUPE, PARA LA EXPEDICIÓN DEL CERTIFICADO DE POSESIÓN DE LOTE DE TERRENO A SU FAVOR. ESTA GESTIÓN DEBERÁ SER INICIADA POR <b>“EL PROMITENTE COMPRADOR”</b>, EN EL PLAZO MÁXIMO TRES MESES POSTERIORES A LA SUSCRIPCIÓN DEL ACTA DE ENTREGA DE LOTE DE TERRENO. DE <b>“EL PROMITENTE VENDEDOR”.</b> 1) ENTREGAR A <b>“EL PROMITENTE COMPRADOR”</b> UN COMPROBANTE O RECIBO DE PAGO POR CADA CUOTA CANCELADA, EN LA FECHA DE REALIZACIÓN DEL PAGO, INDICANDO EN EL TEXTO LA DISTRIBUCIÓN DE LO AMORTIZADO A CAPITAL E INTERESES, DECLARANDO EL SALDO PENDIENTE DE PAGO. 2) ACEPTAR LAS CESIONES DE DERECHOS QUE HAGA <b>“EL PROMITENTE COMPRADOR”</b>, SIEMPRE QUE SE ENCUENTRE AL DÍA CON LOS PAGOS. 3) DESARROLLAR Y EJECUTAR EL PROYECTO DE LOTIZACIÓN <b>“VILLA EL OLIVAR”,</b> TENIENDO COMO PLAZO DE ENTREGA DEL PROYECTO HABILITADO, 24 MESES CONTADOS DESDE LA FIRMA DEL PRESENTE CONTRATO, <span class="highlighted">PRORROGÁNDOSE POR TRES MESES ADICIONALES EN CASO EXISTA UNA DEMORA EN EL DESARROLLO DEL PROCESO DE HABILITACIÓN POR CAUSAS IMPUTABLES CON RESPECTO A LOS PLAZOS ESTABLECIDOS POR LAS ENTIDADES PRESTADORAS DE SERVICIOS PÚBLICOS O CUALQUIER OTRA ENTIDAD PRIVADA QUE INTERVENGA EN DICHO PROCESO, ASIMISMO, SE ESTABLECE UNA PRÓRROGA ADICIONAL DE LA YA ANTERIORMENTE PACTADA, SÓLO PARA ESCENARIOS DE PANDEMIA, ESTADO DE EMERGENCIA, CASOS FORTUITOS DE FUERZA MAYOR COMO POR EJEMPLO DE LA MISMA NATURALEZA, ASÍ COMO TAMBIÉN DE LA RECESIÓN ECONÓMICA SUSCITADA ACTUALMENTE EN NUESTRO PAÍS Y/O OTRAS CIRCUNSTANCIAS NO PREVISTAS O ESTABLECIDAS EN ESTA PRESENTE CLÁUSULA 4) AUNADO A ELLO, SE CUENTA CON PUNTO DE ENTREGA DE LUZ Y AGUA POTABLE, QUEDANDO A SOLICITUD DEL COMPRADOR LA REALIZACIÓN DE INSTALACIÓN DE SU POSTE Y SUMINISTRO PARA SU INSTALACIÓN DEL MISMO, DEL MISMO MODO, SE ENTREGA UN PARQUE HABILITADO Y PORTICO DE INGRESO. 5) ACOMPAÑAR Y ASESORAR LA GESTIÓN ANTE LA COMUNIDAD CAMPESINA “SAN JULIÁN” DE MOTUPE, PARA LA EXPEDICIÓN DEL CERTIFICADO DE POSESIÓN, SE ACOMPAÑARÁ Y GESTIONARÁ EL CERTIFICADO DE POSESIÓN EN LA MUNICIPALIDAD DE ANCHOVIRA DE LOTE DE TERRENO A FAVOR DE <b>“EL PROMITENTE COMPRADOR”.</b></span>
    </p>
  </div>

  <div class="clause">
    <p><b><u>CLÁUSULA SEXTA:</u></b></p>
    <p>EL TRASPASO DE POSESIÓN DEL LOTE DESCRITO EN LA CLÁUSULA TERCERA, COMPRENDE LA POSESIÓN SOBRE EL REFERIDO BIEN INMUEBLE, LAS MEJORAS EFECTUADAS SOBRE EL, SUS AIRES, ENTRADAS, SALIDAS, USOS Y COSTUMBRES, SERVIDUMBRES, Y DEMÁS DERECHOS INHERENTES A LA POSESIÓN, SIN RESERVA NI LIMITACIÓN ALGUNA. QUEDA ESTABLECIDO DE MANERA EXPRESA QUE <b>“EL PROMITENTE VENDEDOR”</b>, ENTREGARÁ EN FORMA PACÍFICA EL LOTE DE TERRENO, AL MOMENTO DE SUSCRIBIR EL ACTA DE ENTREGA DE LOTE DE TERRENO, FECHA A PARTIR DE LA CUAL <b>“EL PROMITENTE COMPRADOR”</b>, PODRÁ EJERCER LA POSESIÓN Y CONDUCCIÓN DEL MISMO.
    </p>
  </div>

  <div class="clause">
    <p><b><u>CLÁUSULA SÉPTIMA:</u></b></p>
    <p>AMBAS PARTES, DECLARAN QUE CELEBRAN EL PRESENTE CONTRATO VOLUNTARIAMENTE Y SIN COACCIÓN ALGUNA Y QUE NO HA MEDIADO NINGÚN VICIO DE LA VOLUNTAD NO EXISTIENDO DOLO, SIMULACIÓN O VICIO ALGUNO QUE PUDIERA INVALIDAR EL ACTO, RENUNCIANDO EXPRESAMENTE A CUALQUIER RECLAMO JUDICIAL POSTERIOR AL RESPECTO. ASIMISMO, <b>“EL PROMITENTE VENDEDOR”</b>”, DECLARA QUE SOBRE EL LOTE DE TERRENO MATERIA DE TRASPASO NO PESA NINGÚN GRAVAMEN, DEUDA O EMBARGO QUE PUDIERA LIMITAR SU LIBRE TRANSMISIÓN, ASUMIENDO LOS DAÑOS Y PERJUICIOS EN CASO DE FALSEDAD. POR SU PARTE, <b>“EL PROMITENTE COMPRADOR”</b> DEJA EXPRESA MANIFESTACIÓN QUE CON ANTERIORIDAD A LA SUSCRIPCIÓN DEL PRESENTE CONTRATO, HA VERIFICADO LA POSESIÓN, SITUACIÓN FÍSICA, MUNICIPAL, REGISTRAL Y DE SERVICIOS BÁSICOS DEL LOTE DE TERRENO OBJETO DEL PRESENTE CONTRATO, EXPRESANDO QUE EL LOTE DE TERRENO QUE ADQUIERE SE ENCUENTRA A SU ENTERA Y TOTAL SATISFACCIÓN.
    </p>
  </div>

  <div class="clause">
    <p><b>DEL DOMICILIO Y COMPETENCIA</b></p>
    <p><b><u>CLÁUSULA OCTAVA:</u></b></p>
    <p>LAS PARTES INTERVINIENTES EN ESTE CONTRATO DECLARAN SUS DOMICILIOS LOS CONSIGNADOS AL INICIO DEL PRESENTE DOCUMENTO, LUGAR DONDE SE DEBERÁN CURSAR TODO TIPO DE COMUNICACIONES JUDICIALES O EXTRAJUDICIALES. CUALQUIER CAMBIO DE DOMICILIO DEBERÁ SER PUESTO EN CONOCIMIENTO DE LAS PARTES MEDIANTE COMUNICACIÓN NOTARIAL, CASO CONTRARIO SE MANTENDRÁ COMO VÁLIDA CUALQUIER COMUNICACIÓN DIRIGIDA AL DOMICILIO CONSIGNADO AL INICIO DEL PRESENTE.</p>
        <p> ASIMISMO, SE SOMETEN EXPRESAMENTE A LA COMPETENCIA DE LOS JUECES Y TRIBUNALES DE LA CIUDAD DE CHICLAYO.
    </p>
  </div>

  <div class="clause">
    <p><b>CONSTRUCCIONES Y/O MEJORAS</b></p>
    <p><b><u>CLÁUSULA NOVENA:</u></b></p>
    <p><b>“EL PROMITENTE COMPRADOR”</b> PODRÁ REALIZAR CONSTRUCCIONES Y/O MEJORAS SOBRE EL INMUEBLE RELACIONADO, PREVIA ACEPTACIÓN POR ESCRITO DE <b>“EL PROMITENTE VENDEDOR”</b>. 
        EN CASO DE TERMINACIÓN DEL CONTRATO POR DESISTIMIENTO, <b>“EL PROMITENTE COMPRADOR”</b> PERDERÁ EL VALOR DE LAS CONSTRUCCIONES O MEJORAS AUTORIZADAS, YA QUE
        CORRERÁN A FAVOR DE <b>“EL PROMITENTE VENDEDOR”</b>, POR LO QUE RENUNCIA A RECLAMO ALGUNO POR DICHA CONSTRUCCIÓN Y MEJORA DEL INMUEBLE.
    </p>
  </div>

  <div class="clause">
  <p><b>REGLAS CONCERNIENTES A LA CESIÓN DE LA POSICIÓN CONTRACTUAL </b></p>
  <p><b><u>CLÁUSULA DÉCIMA:</u></b></p>
    <p><b>“EL PROMITENTE COMPRADOR”</b> TAL COMO SE HA ESTABLECIDO EN EL PRESENTE CONTRATO, PUEDE CEDER SU POSICIÓN EN EL CONTRATO A FAVOR DE TERCEROS PARA TODOS LOS EFECTOS HASTA ANTES DE LA ENTREGA DEL PROYECTO Y CONFORME A DERECHO CORRESPONDE. PARA EL CASO, QUIEN SE CONSTITUYA EN CESIONARIO ASUMIRÁ TODOS LOS
    <span class="highlighted">DERECHOS Y OBLIGACIONES QUE LE COMPETEN; ESTIPULADO EN EL ARTÍCULO 1435 DE NUESTRO CÓDIGO CIVIL. LO CUAL ESTIPULA LO SIGUIENTE:</p>
    <p><b><span class="highlighted">“EN LOS CONTRATOS CON PRESTACIONES NO EJECUTADAS TOTAL O PARCIALMENTE, CUALQUIERA DE LAS PARTES PUEDE CEDER A UN TERCERO SU POSICIÓN CONTRACTUAL. SE REQUIERE QUE LA OTRA PARTE PRESTE SU CONFORMIDAD ANTES, SIMULTÁNEAMENTE O DESPUÉS DEL ACURDO DE CESIÓN.</p>
    <p><span class="highlighted">SI LA CONFORMIDAD DEL CEDIDO HUBIERA SIDO PRESTADA PREVIAMENTE AL ACUERDO ENTRE CEDENTE Y CESIONARIO, EL CONTRATO SÓLO TENDRÁ EFECTOS DESDE QUE DICHO ACUERDO HAYA SIDO COMUNICADO AL CEDIDO POR ESCRITO DE FECHA CIERTA.”</b></p>
    <p>EN CONSECUENCIA, <b>“EL PROMITENTE COMPRADOR”</b>”, DEJA CONSTANCIA QUE AL TENER ALGUNA SITUACIÓN DE ENFERMEDAD GRAVE O MUERTE, CEDE SU POSICIÓN A FAVOR DE ………………………………………………… IDENTIFICADO CON DNI N° …………….., QUIEN SERÁ LA QUE ASUMA TODOS LOS DERECHOS Y OBLIGACIONES DESCRITAS EN ESTE PRESENTE CONTRATO. PREVIA COMUNICACIÓN CON EL <b>“EL PROMITENTE VENDEDOR”</b>, QUIEN SERÁ EL O LA QUE ASUMA TODOS LOS DERECHOS Y OBLIGACIONES DESCRITAS EN ESTE PRESENTE CONTRATO. RESPECTO A LOS ALCANCES DEL PRESENTE CONTRATO, A PARTIR DE LA FECHA DE SUSCRIPCIÓN NOTARIAL DEL CONTRATO DE CESIÓN Y SU PUESTA A CONOCIMIENTO DE <b>“EL PROMITENTE VENDEDOR”</b> POR LA UNIDAD DE TRÁMITE DOCUMENTARIO OFICIAL EN LA DIRECCIÓN FISCAL CONSIGNADA. </p>
    <p>DESDE ESE 
        MOMENTO, <b>“EL PROMITENTE VENDEDOR”</b> CONSIDERARÁ APARTADO TOTALMENTE AL CEDENTE; DE LA RELACIÓN JURÍDICA PRIMIGENIA, QUEDANDO EL CESIONARIO COMO ÚNICO RESPONSABLE DE TODAS LAS OBLIGACIONES Y DERECHOS ORIGINADAS POR LA SUSCRIPCIÓN DEL PRESENTE CONTRATO. SERÁ OBLIGACIÓN DEL CESIONARIO ASUMIR LOS GASTOS QUE SE GENERASEN A <b>“EL PROMITENTE VENDEDOR”</b> CON 
        OCASIÓN DEL ACTO DE CESIÓN DE LA POSICIÓN CONTRACTUAL.</p>

    </p>
  </div>

  <div class="clause">
    <p><b>ESTIPULACIÓN RESOLUTORIA</b></p>
    <p><b><u>CLÁUSULA DÉCIMA PRIMERA:</u></b></p>
    <p>DE COMÚN ACUERDO SE ESTABLECE COMO CONDICIONES PARA QUE OPERE LA RESOLUCIÓN DE PLENO DERECHO A FAVOR DE CUALQUIERA DE LAS PARTES, LAS SIGUIENTES:</p>
    <p>A FAVOR DE <b>“EL PROMITENTE COMPRADOR”</b>:</p>

        <ul>
            <li>QUE <b>“EL PROMITENTE VENDEDOR”</b> NO HAGA ENTREGA FÍSICA EL BIEN, EN PLAZO MÁXIMO DE DOS (02) DÍAS CONTADOS DESDE EL DÍA DE LA FIRMA DEL PRESENTE CONTRATO.</li>
            <li>QUE <b>“EL PROMITENTE VENDEDOR”</b> NO CUMPLA OPORTUNAMENTE CON LOS TRÁMITES Y PROCEDIMIENTOS QUE SEAN NECESARIOS PARA CUMPLIR CON LA PROMESA DE VENTA, POR CAUSA QUE LE SEA IMPUTABLE A TÍTULO DE OMISIÓN DOLOSA O CULPOSA.</li>
            <li>A EFECTOS DE LO DISPUESTO EN ESTA CLÁUSULA SE CONSIDERA OMISIÓN DOLOSA LA INACTIVIDAD Y ABSTENCIÓN TOTAL DE <b>“EL PROMITENTE VENDEDOR”</b> DE INICIAR Y CONCLUIR LOS TRÁMITES Y/O PROCEDIMIENTOS CONDUCENTES A QUE SE PUEDA CUMPLIR LA PROMESA DE VENTA, NO PUDIENDO HACER VALER EXCUSA AL RESPECTO DE NINGUNA NATURALEZA.</li>
            <li>A EFECTOS DE LO DISPUESTO EN ESTA CLÁUSULA SE CONSIDERA OMISIÓN CULPOSA, 1) HABER INICIADO EL TRÁMITE Y ABANDONARLO A CUALQUIER ESTADO DEL MISMO, 2) NO HABER INICIADO EL TRÁMITE SIN QUE MEDIE CAUSA EXTERNA O FUERZA MAYOR QUE AMERITE ESE RETRASO, 3) NO CONCLUIR EL TRÁMITE DENTRO DEL PLAZO FIJADO EN EL PRESENTE CONTRATO SIN QUE MEDIE CAUSA EXTERNA O FUERZA MAYOR QUE AMERITE EL RETRASO.</li> 
            <li>EN CASO DE CAUSA EXTERNA O FUERZA MAYOR <b>“EL PROMITENTE VENDEDOR”</b> COMUNICARÁ EL HECHO GENERADOR, COMO MÁXIMO A LOS VEINTE (20) DÍAS DE HABER INICIADO ÉSTE CON EL DEBIDO SUSTENTO LEGAL Y/O FÁCTICO.</li>
            <li>EN CASO QUE <b>“EL PROMITENTE VENDEDOR”</b> NO COMUNIQUE DE MANERA OPORTUNA DE ESTE HECHO, NO PODRÁ EN NINGÚN SENTIDO Y FORMA JUSTIFICAR EL RETRASO. COMUNICADO EL HECHO GENERADOR, EL PLAZO QUEDARÁ SUSPENDIDO DESDE EL DÍA DEL SUCESO HASTA EL DÍA DE LA TERMINACIÓN DE ÉSTE Y SUS EFECTOS, DEBIENDO TAMBIÉN SER COMUNICADA ESTA TERMINACIÓN COMO MÁXIMO DOS DÍAS DESPUÉS DE SUSCITADA. PARA COBRAR VALIDEZ ESTAS COMUNICACIONES DEBEN SER EXPEDIDAS AL CORREO, WHATSAPP Y/O AL DOMICILIO CONSIGNADO POR <b>“EL PROMITENTE COMPRADOR”</b>.</li>
        </ul>

    <p>A FAVOR DE <b>“EL PROMITENTE VENDEDOR”</b>:</p>

    <ul>
        <li>QUE <b>“EL PROMITENTE COMPRADOR”</b> CUANDO HAYA ADQUIRIDO TAL CONDICIÓN MEDIANTE CESIÓN DE LA POSICIÓN CONTRACTUAL, NO CUMPLA CON LOS GASTOS QUE SE LE REQUIERA EN EL PLAZO MÁXIMO DE TRES (03) DÍAS DE SER SOLICITADO POR CUALQUIER MEDIO QUE ACREDITE RECEPCIÓN.</li>
        <li>CUANDO <b>“EL PROMITENTE COMPRADOR”</b> ALCANCE MÁS DEL 15% DE PENALIDAD POR MORA CON RELACIÓN AL PRECIO TOTAL DEL PRESENTE ACTO JURIDICO. ESTA PENALIDAD SE CALCULARÁ EN RAZÓN A S/.5.00 (CINCO Y 00/100 NUEVOS SOLES) POR CADA DÍA DE RETRASO.</li>
        <li>DESISTIMIENTO POR PARTE DE <b>“EL PROMITENTE COMPRADOR”</b>. CUANDO <b>“EL PROMITENTE COMPRADOR”</b> ACUMULE TRES CUOTAS CONSECUTIVAS IMPAGAS O CINCO NO CONSECUTIVAS EN EL PLAZO DE SIETE MESES.</li>
        <li>QUE <b>“EL PROMITENTE COMPRADOR”</b> NO CONCURRA O RESPONDA A LAS COMUNICACIONES DE <b>“EL PROMITENTE VENDEDOR”</b> CON UN MÁXIMO DE TOLERANCIA O INSISTENCIA DE QUINCE DÍAS, HABIENDO SIDO REQUERIDO POR MEDIO QUE ACREDITE RECEPCIÓN. EN TAL CASO SE CONSIDERARÁ QUE EXISTE ABANDONO, PROCEDIÉNDOSE A LA RESOLUCIÓN CONTRACTUAL CORRESPONDIENTE.</li>
        <li>QUE DURANTE LA VIGENCIA DEL CONTRATO SE DETECTE CON PLENA CERTEZA QUE LOS FONDOS DE <b>“EL PROMITENTE COMPRADOR”</b> PROVIENEN DE LAVADO DE ACTIVOS, EXTORCIÓN, ROBO O DE CUALQUIER FUENTE ILÍCITA Y/O ANTIJURÍDICA.</li>
        <li>EN CUALQUIERA DE LOS CASOS, LAS PARTES ACUERDAN QUE <b>“EL PROMITENTE VENDEDOR”</b> CONSERVARÁ LA PARTE PAGADA EN CALIDAD DE RESARCIMIENTO POR LOS DAÑOS Y PERJUICIOS CAUSADOS POR EL INCUMPLIMIENTO, LO CUAL COMPRENDERÁ LA INMEDIATA RECUPERACIÓN DEL INMUEBLE.</li>

    </ul>
    </div>

    <div class="clause">
    <p>EN SUMA, EL MISMO CÓDIGO CIVIL EN EL <b>ARTÍCULO 1430</b> SEÑALA QUE, <b>“PUEDE CONVENIRSE EXPRESAMENTE QUE EL CONTRATO SE RESUELVA CUANDO UNA DE LAS PARTES NO CUMPLE DETERMINADA PRESTAACIÓN A SU CARGO, ESTABLECIDA CON TODA PRESICIÓN.</p>
    <p>LA RESOLUCIÓN SE PRODUCE DE PLENO DERECHO CUANDO LA PARTE INTERESADA COMUNICA A LA OTRA QUE QUIERE VALERSE DE LA CLÁUSULA RESOLUTORIA.” </b></p>
    <p> DE LA MISMA FORMA Y ACTUANDO DE ACUERDO A LEY CON RESPECTO AL PROCEDIMIENTO EL ART. 1429 DEL CÓDIGO CIVIL, DISPONE QUE, LA PARTE QUE SE PERJUDICA CON EL INCUMPLIMIENTO DE LA OTRA, LE REQUERIRÁ MEDIANTE CARTA POR VÍA NOTARIAL QUE SATISFAGA SU PRESTACIÓN, DENTRO DE UN PLAZO NO MENOR DE QUINCE DÍAS, BAJO APERCIBIMIENTO DE QUE, EN CASO CONTRARIO, EL CONTRATO QUEDA RESUELTO. SI LA PRESTACIÓN NO SE CUMPLE DENTRO DEL PLAZO SEÑALADO, EL CONTRATO SE RESUELVE DE PLENO DERECHO, QUEDANDO A CARGO DEL DEUDOR LA INDEMNIZACIÓN DE DAÑOS Y PERJUICIOS</p>
    <p><b>SOLUCIÓN DE CONFLICTOS CLÁUSULA DÉCIMO SEGUNDA:</b></p>
    <p>LAS DISCREPANCIAS, DIFERENCIAS O DISPUTAS QUE SURGIEREN ENTRE LAS PARTES CON RELACIÓN AL PRESENTE CONTRATO, SERÁN DECIDIDAS EN PARTICULAR POR ARREGLO DIRECTO Y DE NO SOLVENTARSE LA SOLUCIÓN POR ESTA VÍA, POR MEDIOS ALTERNOS DE SOLUCIÓN DE CONTROVERSIAS, DE CONFORMIDAD A LA LEY DE PROTECCIÓN AL CONSUMIDOR O EN SU DEFECTO LA LEY DE MEDIACIÓN, CONCILIACIÓN Y ARBITRAJE. LO ANTERIOR SIN PERJUICIO DE LA ACCIÓN JUDICIAL QUE PUEDA INICIARSE.</p>
    <p>EN CONFORMIDAD FIRMAN LAS PARTES, A LOS <b>XXXX</b> DÍAS DEL MES DE <b>XXXXX</b> DEL DOS MIL VEINTICUATRO ANTE NOTARIO PÚBLICO EN LA CIUDAD DE CHICLAYO. </p>
    <br>
    <h2>“INMOBILIARIA Y CONSTRUCTORA ALITORRES E.I.R.L”</h2>

    </div>
    
    <div class="signature-container">
    <div class="signature">
        <p>____________________________</p>
        <p>ELVIS TORRES SALDAÑA</p>
        <p>DNI Nº 42225869</p>
        <p>“EL PROMITENTE VENDEDOR”</p>
    </div>

    <div class="signature">
        <p>____________________________</p>
        <p>XXXXXX XXXXX XXXXX</p>
        <p>DNI N.º XXXXXXXX</p>
        <p>“EL PROMITENTE COMPRADOR”</p>
    </div>
</div>

    <div class="clause">
    <br><br><br>
    <h2>PAGO COMPLETO DE TERRENO MZ. XX LOTE XXX / OP:</h2>
    <h2>SE PEGAN LOS VOUCHER AQUI</h2>
    </div>

</body>
</html>